name: maintenance

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: mkdir -p ~/.ssh && printf "%s\n" "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

      - uses: jdx/mise-action@v2

      - run: mise run maintenance
